namespace Todl.Compiler.CodeAnalysis.Syntax
{
    public enum SyntaxKind
    {
        // Tokens
        BadToken,
        EndOfFileToken,
        NumberToken,
        StringToken,
        PlusToken,
        PlusEqualsToken,
        MinusToken,
        MinusEqualsToken,
        StarToken,
        StarEqualsToken,
        SlashToken,
        SlashEqualsToken,
        OpenParenthesisToken,
        CloseParenthesisToken,
        OpenBraceToken,
        CloseBraceToken,
        OpenBracketToken,
        CloseBracketToken,
        SemicolonToken,
        ColonToken,
        EqualsToken,
        EqualsEqualsToken,
        BangToken,
        BangEqualsToken,
        LessThanToken,
        LessThanOrEqualsToken,
        GreaterThanToken,
        GreaterThanOrEqualsToken,
        AmpersandToken,
        AmpersandAmpersandToken,
        PipeToken,
        PipePipeToken,
        TildeToken,
        DotToken,
        CommaToken,
        IdentifierToken,

        // Keywords
        TrueKeywordToken,
        FalseKeywordToken,
        ConstKeywordToken,
        LetKeywordToken,
        ImportKeywordToken,
        FromKeywordToken,
        NewKeywordToken,
        BoolKeywordToken,
        ByteKeywordToken,
        CharKeywordToken,
        IntKeywordToken,
        LongKeywordToken,
        StringKeywordToken,
        VoidKeywordToken,
        ReturnKeywordToken,
        IfKeywordToken,
        UnlessKeywordToken,
        ElseKeywordToken,
        WhileKeywordToken,
        UntilKeywordToken,
        BreakKeywordToken,
        ContinueKeywordToken,

        // Trivia
        WhitespaceTrivia,
        LineBreakTrivia,
        SingleLineCommentTrivia
    }
}
